[2024-05-24T11:08:10.955+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-24T11:08:10.979+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_weather_workflow_DAG_v03.transform_data_response manual__2024-05-24T10:45:36.975501+00:00 [queued]>
[2024-05-24T11:08:10.988+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_weather_workflow_DAG_v03.transform_data_response manual__2024-05-24T10:45:36.975501+00:00 [queued]>
[2024-05-24T11:08:10.989+0000] {taskinstance.py:2306} INFO - Starting attempt 6 of 11
[2024-05-24T11:08:11.005+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data_response> on 2024-05-24 10:45:36.975501+00:00
[2024-05-24T11:08:11.012+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_weather_workflow_DAG_v03', 'transform_data_response', 'manual__2024-05-24T10:45:36.975501+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp1z7k32ig']
[2024-05-24T11:08:11.015+0000] {standard_task_runner.py:91} INFO - Job 53: Subtask transform_data_response
[2024-05-24T11:08:11.016+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1881) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-24T11:08:11.017+0000] {standard_task_runner.py:63} INFO - Started process 1883 to run task
[2024-05-24T11:08:11.077+0000] {task_command.py:426} INFO - Running <TaskInstance: my_weather_workflow_DAG_v03.transform_data_response manual__2024-05-24T10:45:36.975501+00:00 [running]> on host 6ab40057742d
[2024-05-24T11:08:11.393+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Khang' AIRFLOW_CTX_DAG_ID='my_weather_workflow_DAG_v03' AIRFLOW_CTX_TASK_ID='transform_data_response' AIRFLOW_CTX_EXECUTION_DATE='2024-05-24T10:45:36.975501+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-24T10:45:36.975501+00:00'
[2024-05-24T11:08:11.394+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-24T11:08:11.430+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-24T11:08:11.431+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/weather_dag.py", line 48, in transform_data
    to_csv(transformed_data)
  File "/opt/airflow/dags/weather_dag.py", line 56, in to_csv
    directory = f'{os.path.dirname()}/data-transformed'
                   ^^^^^^^^^^^^^^^^^
TypeError: dirname() missing 1 required positional argument: 'p'
[2024-05-24T11:08:11.453+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=my_weather_workflow_DAG_v03, task_id=transform_data_response, run_id=manual__2024-05-24T10:45:36.975501+00:00, execution_date=20240524T104536, start_date=20240524T110810, end_date=20240524T110811
[2024-05-24T11:08:11.469+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 53 for task transform_data_response (dirname() missing 1 required positional argument: 'p'; 1883)
[2024-05-24T11:08:11.514+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-24T11:08:11.536+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-24T11:08:11.538+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
