[2024-06-01T04:26:12.879+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-01T04:26:12.906+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_weather_workflow_DAG_v04.group_tasks.extract_weather_data_from_api manual__2024-06-01T04:21:04.663663+00:00 [queued]>
[2024-06-01T04:26:12.917+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_weather_workflow_DAG_v04.group_tasks.extract_weather_data_from_api manual__2024-06-01T04:21:04.663663+00:00 [queued]>
[2024-06-01T04:26:12.919+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 7
[2024-06-01T04:26:12.934+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): group_tasks.extract_weather_data_from_api> on 2024-06-01 04:21:04.663663+00:00
[2024-06-01T04:26:12.942+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_weather_workflow_DAG_v04', 'group_tasks.extract_weather_data_from_api', 'manual__2024-06-01T04:21:04.663663+00:00', '--job-id', '458', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpwo_pktih']
[2024-06-01T04:26:12.946+0000] {standard_task_runner.py:91} INFO - Job 458: Subtask group_tasks.extract_weather_data_from_api
[2024-06-01T04:26:12.947+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3561) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-01T04:26:12.948+0000] {standard_task_runner.py:63} INFO - Started process 3563 to run task
[2024-06-01T04:26:13.015+0000] {task_command.py:426} INFO - Running <TaskInstance: my_weather_workflow_DAG_v04.group_tasks.extract_weather_data_from_api manual__2024-06-01T04:21:04.663663+00:00 [running]> on host cd9caf1c47f0
[2024-06-01T04:26:13.165+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Khang' AIRFLOW_CTX_DAG_ID='my_weather_workflow_DAG_v04' AIRFLOW_CTX_TASK_ID='group_tasks.extract_weather_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T04:21:04.663663+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-01T04:21:04.663663+00:00'
[2024-06-01T04:26:13.167+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-01T04:26:13.181+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-01T04:26:13.182+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/weather_dag.py", line 117, in extract_weather_data_from_api
    operator = SimpleHttpOperator(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseOperator.__init__() missing 1 required positional argument: 'task_id'
[2024-06-01T04:26:13.204+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=my_weather_workflow_DAG_v04, task_id=group_tasks.extract_weather_data_from_api, run_id=manual__2024-06-01T04:21:04.663663+00:00, execution_date=20240601T042104, start_date=20240601T042612, end_date=20240601T042613
[2024-06-01T04:26:13.219+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 458 for task group_tasks.extract_weather_data_from_api (BaseOperator.__init__() missing 1 required positional argument: 'task_id'; 3563)
[2024-06-01T04:26:13.243+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-01T04:26:13.274+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-01T04:26:13.277+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
