[2024-06-01T15:11:10.797+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-01T15:11:10.827+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_weather_workflow_DAG_v04.group_tasks.check_data_city_is_exist manual__2024-06-01T14:44:02.662915+00:00 [queued]>
[2024-06-01T15:11:10.844+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_weather_workflow_DAG_v04.group_tasks.check_data_city_is_exist manual__2024-06-01T14:44:02.662915+00:00 [queued]>
[2024-06-01T15:11:10.845+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 9
[2024-06-01T15:11:10.873+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): group_tasks.check_data_city_is_exist> on 2024-06-01 14:44:02.662915+00:00
[2024-06-01T15:11:10.886+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_weather_workflow_DAG_v04', 'group_tasks.check_data_city_is_exist', 'manual__2024-06-01T14:44:02.662915+00:00', '--job-id', '775', '--raw', '--subdir', 'DAGS_FOLDER/tasks_flow.py', '--cfg-path', '/tmp/tmp91ksi744']
[2024-06-01T15:11:10.891+0000] {standard_task_runner.py:91} INFO - Job 775: Subtask group_tasks.check_data_city_is_exist
[2024-06-01T15:11:10.896+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1234) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-01T15:11:10.898+0000] {standard_task_runner.py:63} INFO - Started process 1236 to run task
[2024-06-01T15:11:10.972+0000] {task_command.py:426} INFO - Running <TaskInstance: my_weather_workflow_DAG_v04.group_tasks.check_data_city_is_exist manual__2024-06-01T14:44:02.662915+00:00 [running]> on host cd9caf1c47f0
[2024-06-01T15:11:11.080+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Khang' AIRFLOW_CTX_DAG_ID='my_weather_workflow_DAG_v04' AIRFLOW_CTX_TASK_ID='group_tasks.check_data_city_is_exist' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T14:44:02.662915+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-01T14:44:02.662915+00:00'
[2024-06-01T15:11:11.082+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-01T15:11:11.095+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-06-01T15:11:11.124+0000] {base.py:84} INFO - Using connection ID 'postgres_connection_id' for task execution.
[2024-06-01T15:11:11.132+0000] {sql.py:470} INFO - Running statement: SELECT COUNT(*) FROM cities WHERE wiki_id = 'Q36167';, parameters: None
[2024-06-01T15:11:11.134+0000] {sql.py:479} INFO - Rows affected: 1
[2024-06-01T15:11:11.136+0000] {python.py:237} INFO - Done. Returned value was: group_tasks.delete_file_city
[2024-06-01T15:11:11.136+0000] {branch.py:36} INFO - Branch into group_tasks.delete_file_city
[2024-06-01T15:11:11.137+0000] {skipmixin.py:178} INFO - Following branch group_tasks.delete_file_city
[2024-06-01T15:11:11.138+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-01T15:11:11.151+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 269, in execute
    return self.do_branch(context, super().execute(context))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/branch.py", line 37, in do_branch
    self.skip_all_except(context["ti"], branches_to_execute)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/skipmixin.py", line 215, in skip_all_except
    raise AirflowException(
airflow.exceptions.AirflowException: 'branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'group_tasks.delete_file_city'}.
[2024-06-01T15:11:11.155+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=my_weather_workflow_DAG_v04, task_id=group_tasks.check_data_city_is_exist, run_id=manual__2024-06-01T14:44:02.662915+00:00, execution_date=20240601T144402, start_date=20240601T151110, end_date=20240601T151111
[2024-06-01T15:11:11.169+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 775 for task group_tasks.check_data_city_is_exist ('branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'group_tasks.delete_file_city'}.; 1236)
[2024-06-01T15:11:11.194+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-01T15:11:11.228+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-06-01T15:11:11.248+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-01T15:11:11.251+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
