[2024-05-31T04:53:17.470+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-31T04:53:17.491+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_weather_workflow_DAG_v04.delete_file_city manual__2024-05-31T04:06:10.739308+00:00 [queued]>
[2024-05-31T04:53:17.499+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_weather_workflow_DAG_v04.delete_file_city manual__2024-05-31T04:06:10.739308+00:00 [queued]>
[2024-05-31T04:53:17.500+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 6
[2024-05-31T04:53:17.514+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): delete_file_city> on 2024-05-31 04:06:10.739308+00:00
[2024-05-31T04:53:17.523+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2571) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-31T04:53:17.524+0000] {standard_task_runner.py:63} INFO - Started process 2573 to run task
[2024-05-31T04:53:17.523+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_weather_workflow_DAG_v04', 'delete_file_city', 'manual__2024-05-31T04:06:10.739308+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmptmo785p7']
[2024-05-31T04:53:17.526+0000] {standard_task_runner.py:91} INFO - Job 204: Subtask delete_file_city
[2024-05-31T04:53:17.587+0000] {task_command.py:426} INFO - Running <TaskInstance: my_weather_workflow_DAG_v04.delete_file_city manual__2024-05-31T04:06:10.739308+00:00 [running]> on host cd9caf1c47f0
[2024-05-31T04:53:17.685+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Khang' AIRFLOW_CTX_DAG_ID='my_weather_workflow_DAG_v04' AIRFLOW_CTX_TASK_ID='delete_file_city' AIRFLOW_CTX_EXECUTION_DATE='2024-05-31T04:06:10.739308+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-31T04:06:10.739308+00:00'
[2024-05-31T04:53:17.686+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-31T04:53:17.713+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-31T04:53:17.714+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/weather_dag.py", line 160, in delete_file
    os.remove(f'/opt/airflow/data-transformed/{file_name}')
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data-transformed/None'
[2024-05-31T04:53:17.733+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=my_weather_workflow_DAG_v04, task_id=delete_file_city, run_id=manual__2024-05-31T04:06:10.739308+00:00, execution_date=20240531T040610, start_date=20240531T045317, end_date=20240531T045317
[2024-05-31T04:53:17.746+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 204 for task delete_file_city ([Errno 2] No such file or directory: '/opt/airflow/data-transformed/None'; 2573)
[2024-05-31T04:53:17.780+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-31T04:53:17.799+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-31T04:53:17.802+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
