[2024-05-25T15:45:48.957+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-25T15:45:48.988+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_weather_workflow_DAG_v03.up_load_to_s3 manual__2024-05-25T15:22:35.369972+00:00 [queued]>
[2024-05-25T15:45:49.000+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_weather_workflow_DAG_v03.up_load_to_s3 manual__2024-05-25T15:22:35.369972+00:00 [queued]>
[2024-05-25T15:45:49.002+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 9
[2024-05-25T15:45:49.025+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): up_load_to_s3> on 2024-05-25 15:22:35.369972+00:00
[2024-05-25T15:45:49.036+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2894) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-25T15:45:49.038+0000] {standard_task_runner.py:63} INFO - Started process 2896 to run task
[2024-05-25T15:45:49.036+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_weather_workflow_DAG_v03', 'up_load_to_s3', 'manual__2024-05-25T15:22:35.369972+00:00', '--job-id', '160', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpdxdgu9j7']
[2024-05-25T15:45:49.040+0000] {standard_task_runner.py:91} INFO - Job 160: Subtask up_load_to_s3
[2024-05-25T15:45:49.130+0000] {task_command.py:426} INFO - Running <TaskInstance: my_weather_workflow_DAG_v03.up_load_to_s3 manual__2024-05-25T15:22:35.369972+00:00 [running]> on host c0a968b5acd8
[2024-05-25T15:45:49.242+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Khang' AIRFLOW_CTX_DAG_ID='my_weather_workflow_DAG_v03' AIRFLOW_CTX_TASK_ID='up_load_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-05-25T15:22:35.369972+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-25T15:22:35.369972+00:00'
[2024-05-25T15:45:49.243+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-25T15:45:49.286+0000] {base.py:84} INFO - Using connection ID 'weather_map_s3_connection' for task execution.
[2024-05-25T15:45:49.287+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='weather_map_s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-05-25T15:45:51.062+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-25T15:45:51.064+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-25T15:45:51.077+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=my_weather_workflow_DAG_v03, task_id=up_load_to_s3, run_id=manual__2024-05-25T15:22:35.369972+00:00, execution_date=20240525T152235, start_date=20240525T154548, end_date=20240525T154551
[2024-05-25T15:45:51.103+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-25T15:45:51.128+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-25T15:45:51.132+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
