[2024-05-30T11:27:05.142+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-30T11:27:05.169+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_weather_workflow_DAG_v04.is_city_api_ready manual__2024-05-30T03:47:59.479456+00:00 [queued]>
[2024-05-30T11:27:05.180+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_weather_workflow_DAG_v04.is_city_api_ready manual__2024-05-30T03:47:59.479456+00:00 [queued]>
[2024-05-30T11:27:05.181+0000] {taskinstance.py:2306} INFO - Starting attempt 22 of 27
[2024-05-30T11:27:05.197+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): is_city_api_ready> on 2024-05-30 03:47:59.479456+00:00
[2024-05-30T11:27:05.206+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_weather_workflow_DAG_v04', 'is_city_api_ready', 'manual__2024-05-30T03:47:59.479456+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpkln3_up3']
[2024-05-30T11:27:05.210+0000] {standard_task_runner.py:91} INFO - Job 158: Subtask is_city_api_ready
[2024-05-30T11:27:05.210+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2395) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-30T11:27:05.211+0000] {standard_task_runner.py:63} INFO - Started process 2397 to run task
[2024-05-30T11:27:05.289+0000] {task_command.py:426} INFO - Running <TaskInstance: my_weather_workflow_DAG_v04.is_city_api_ready manual__2024-05-30T03:47:59.479456+00:00 [running]> on host cd9caf1c47f0
[2024-05-30T11:27:05.399+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Khang' AIRFLOW_CTX_DAG_ID='my_weather_workflow_DAG_v04' AIRFLOW_CTX_TASK_ID='is_city_api_ready' AIRFLOW_CTX_EXECUTION_DATE='2024-05-30T03:47:59.479456+00:00' AIRFLOW_CTX_TRY_NUMBER='22' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-30T03:47:59.479456+00:00'
[2024-05-30T11:27:05.402+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-30T11:27:05.416+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-30T11:27:05.416+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/weather_dag.py", line 143, in is_api_ready
    sensor.poke()
TypeError: HttpSensor.poke() missing 1 required positional argument: 'context'
[2024-05-30T11:27:05.438+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=my_weather_workflow_DAG_v04, task_id=is_city_api_ready, run_id=manual__2024-05-30T03:47:59.479456+00:00, execution_date=20240530T034759, start_date=20240530T112705, end_date=20240530T112705
[2024-05-30T11:27:05.449+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 158 for task is_city_api_ready (HttpSensor.poke() missing 1 required positional argument: 'context'; 2397)
[2024-05-30T11:27:05.467+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-30T11:27:05.492+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-30T11:27:05.495+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
