[2024-05-31T04:57:17.354+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-31T04:57:17.378+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_weather_workflow_DAG_v04.check_data_is_exist manual__2024-05-31T04:06:10.739308+00:00 [queued]>
[2024-05-31T04:57:17.387+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_weather_workflow_DAG_v04.check_data_is_exist manual__2024-05-31T04:06:10.739308+00:00 [queued]>
[2024-05-31T04:57:17.388+0000] {taskinstance.py:2306} INFO - Starting attempt 5 of 10
[2024-05-31T04:57:17.402+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): check_data_is_exist> on 2024-05-31 04:06:10.739308+00:00
[2024-05-31T04:57:17.411+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2694) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-31T04:57:17.412+0000] {standard_task_runner.py:63} INFO - Started process 2696 to run task
[2024-05-31T04:57:17.411+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_weather_workflow_DAG_v04', 'check_data_is_exist', 'manual__2024-05-31T04:06:10.739308+00:00', '--job-id', '209', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmppqrd8xqv']
[2024-05-31T04:57:17.414+0000] {standard_task_runner.py:91} INFO - Job 209: Subtask check_data_is_exist
[2024-05-31T04:57:17.475+0000] {task_command.py:426} INFO - Running <TaskInstance: my_weather_workflow_DAG_v04.check_data_is_exist manual__2024-05-31T04:06:10.739308+00:00 [running]> on host cd9caf1c47f0
[2024-05-31T04:57:17.573+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Khang' AIRFLOW_CTX_DAG_ID='my_weather_workflow_DAG_v04' AIRFLOW_CTX_TASK_ID='check_data_is_exist' AIRFLOW_CTX_EXECUTION_DATE='2024-05-31T04:06:10.739308+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-31T04:06:10.739308+00:00'
[2024-05-31T04:57:17.575+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-31T04:57:17.587+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-05-31T04:57:17.613+0000] {base.py:84} INFO - Using connection ID 'postgres_connection_id' for task execution.
[2024-05-31T04:57:17.624+0000] {sql.py:470} INFO - Running statement: SELECT COUNT(*) FROM cities WHERE wiki_id = 'Q19491';, parameters: None
[2024-05-31T04:57:17.627+0000] {sql.py:479} INFO - Rows affected: 1
[2024-05-31T04:57:17.628+0000] {python.py:237} INFO - Done. Returned value was: load_csv_to_postgres
[2024-05-31T04:57:17.629+0000] {branch.py:36} INFO - Branch into load_csv_to_postgres
[2024-05-31T04:57:17.630+0000] {skipmixin.py:178} INFO - Following branch load_csv_to_postgres
[2024-05-31T04:57:17.671+0000] {skipmixin.py:246} INFO - Skipping tasks [('skip_insert_data_city', -1)]
[2024-05-31T04:57:17.709+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-31T04:57:17.738+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=my_weather_workflow_DAG_v04, task_id=check_data_is_exist, run_id=manual__2024-05-31T04:06:10.739308+00:00, execution_date=20240531T040610, start_date=20240531T045717, end_date=20240531T045717
[2024-05-31T04:57:17.788+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-31T04:57:17.828+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-31T04:57:17.832+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
