[2024-05-30T05:58:14.313+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-30T05:58:14.340+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_weather_workflow_DAG_v04.check_data_is_exist manual__2024-05-30T03:47:59.479456+00:00 [queued]>
[2024-05-30T05:58:14.349+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_weather_workflow_DAG_v04.check_data_is_exist manual__2024-05-30T03:47:59.479456+00:00 [queued]>
[2024-05-30T05:58:14.350+0000] {taskinstance.py:2306} INFO - Starting attempt 14 of 19
[2024-05-30T05:58:14.364+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): check_data_is_exist> on 2024-05-30 03:47:59.479456+00:00
[2024-05-30T05:58:14.371+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4782) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-30T05:58:14.372+0000] {standard_task_runner.py:63} INFO - Started process 4784 to run task
[2024-05-30T05:58:14.371+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_weather_workflow_DAG_v04', 'check_data_is_exist', 'manual__2024-05-30T03:47:59.479456+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpmmwrrsu1']
[2024-05-30T05:58:14.373+0000] {standard_task_runner.py:91} INFO - Job 125: Subtask check_data_is_exist
[2024-05-30T05:58:14.440+0000] {task_command.py:426} INFO - Running <TaskInstance: my_weather_workflow_DAG_v04.check_data_is_exist manual__2024-05-30T03:47:59.479456+00:00 [running]> on host cd9caf1c47f0
[2024-05-30T05:58:14.539+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Khang' AIRFLOW_CTX_DAG_ID='my_weather_workflow_DAG_v04' AIRFLOW_CTX_TASK_ID='check_data_is_exist' AIRFLOW_CTX_EXECUTION_DATE='2024-05-30T03:47:59.479456+00:00' AIRFLOW_CTX_TRY_NUMBER='14' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-30T03:47:59.479456+00:00'
[2024-05-30T05:58:14.540+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-30T05:58:14.553+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-05-30T05:58:14.579+0000] {base.py:84} INFO - Using connection ID 'postgres_connection_id' for task execution.
[2024-05-30T05:58:14.587+0000] {sql.py:470} INFO - Running statement: SELECT COUNT(*) FROM cities WHERE wiki_id = 'Q1854';, parameters: None
[2024-05-30T05:58:14.589+0000] {sql.py:479} INFO - Rows affected: 1
[2024-05-30T05:58:14.590+0000] {python.py:237} INFO - Done. Returned value was: load_csv_to_postgres
[2024-05-30T05:58:14.591+0000] {branch.py:36} INFO - Branch into load_csv_to_postgres
[2024-05-30T05:58:14.591+0000] {skipmixin.py:178} INFO - Following branch load_csv_to_postgres
[2024-05-30T05:58:14.620+0000] {skipmixin.py:246} INFO - Skipping tasks [('skip_insert_data_city', -1)]
[2024-05-30T05:58:14.649+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-30T05:58:14.676+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=my_weather_workflow_DAG_v04, task_id=check_data_is_exist, run_id=manual__2024-05-30T03:47:59.479456+00:00, execution_date=20240530T034759, start_date=20240530T055814, end_date=20240530T055814
[2024-05-30T05:58:14.708+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-30T05:58:14.768+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-30T05:58:14.771+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
